version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    image: python:3.10-slim
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: python -m http.server 5500
    ports:
      - "5500:5500"